spring.application.name=veterinaria-bff
server.port=8080

# URLs de los servicios
clientes.url=${CLIENTES_URL:http://localhost:8082}
usuarios.url=${USUARIOS_URL:http://localhost:7071}
roles.url=${ROLES_URL:http://localhost:7071}